version: '3'

services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - CHAT_MODEL_NAME=${CHAT_MODEL_NAME}
    volumes:
      - /data/uploads:/app/uploads
      - /data/chroma_new:/app/KE_MING_BACK/chroma_new
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 